blank_issues_enabled: false
contact_links:
  - name: Fragen / Diskussion
    url: https://github.com/AlexBuchnerTeacher/reflecto/discussions
    about: FÃ¼r allgemeine Fragen oder Ideenaustausch bitte Discussions nutzen.
